# ==============================================================================
# CONFIGURAÇÕES DA APLICAÇÃO
# ==============================================================================
spring.application.name=javanfood
spring.messages.encoding=UTF-8
# ==============================================================================
# BANCO DE DADOS & POOL (HIKARI)
# ==============================================================================
spring.datasource.url=jdbc:postgresql://${db_endress:localhost}:${db_port:5432}/${db_name:javan_food}
spring.datasource.username=${db_user:postgres}
spring.datasource.password=${db_password:admin}
spring.datasource.hikari.connection-timeout=${hikari_connection:3000}
spring.datasource.driver-class-name=org.postgresql.Driver
# ==============================================================================
# JPA / HIBERNATE
# ==============================================================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=sc_javan_food
# ==============================================================================
# MIGRATIONS (FLYWAY)
# ==============================================================================
spring.flyway.locations=${flyway_root:classpath:db/migration,classpath:db/testdata}
spring.flyway.schemas=sc_javan_food
spring.flyway.create-schemas=true
# ==============================================================================
# SERIALIZAÇÃO (JACKSON)
# ==============================================================================
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.deserialization.fail-on-ignored-properties=true
# ==============================================================================
# LOGS
# ==============================================================================
logging.level.org.hibernate.tool.schema=ERROR
# ==============================================================================
# SWAGGER
# ==============================================================================
# ==============================================================================
# ENVERS
# ==============================================================================

